# Nome da aplicação (usado em logs e identificação)
spring.application.name=cryptosentry

# URL de conexão com o banco PostgreSQL
# localhost = sua máquina
# 5432 = porta padrão do Postgres (Docker)
# cryptosentry = nome do banco (tem que existir)
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres

# Usuário do banco (padrão do Postgres)
spring.datasource.username=postgres

# Senha do banco (tem que ser a mesma que você colocou no Docker)
spring.datasource.password=123

# Hibernate vai atualizar/criar tabelas automaticamente
# update = mantém dados e só ajusta estrutura
spring.jpa.hibernate.ddl-auto=create

# Mostra no console os SQL que estão sendo executados
spring.jpa.show-sql=true

# Chave secreta usada para gerar e validar tokens JWT
# (tipo uma senha do sistema)
jwt.secret=minha_chave_secreta

# Tempo de expiração do token JWT (em milissegundos)
# 86400000 = 24 horas
jwt.expiration=86400000